name: mind_horizon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  google_sign_in: ^6.3.0
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  email_otp: ^3.0.2
  flutter_screenutil: ^5.9.3
  video_player: ^2.9.5
  vibration: ^3.1.3
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.0.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

  assets:
    - assets/gif/
    - assets/img/
    - assets/sound/
    - assets/video/
   

  
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins/Poppins-Black.ttf
        - asset: assets/font/Poppins/Poppins-Bold.ttf
        - asset: assets/font/Poppins/Poppins-ExtraBold.ttf
        - asset: assets/font/Poppins/Poppins-ExtraLight.ttf
        - asset: assets/font/Poppins/Poppins-Light.ttf
        - asset: assets/font/Poppins/Poppins-Medium.ttf
        - asset: assets/font/Poppins/Poppins-Regular.ttf
        - asset: assets/font/Poppins/Poppins-SemiBold.ttf
        - asset: assets/font/Poppins/Poppins-Thin.ttf

    - family: Alegreya
      fonts:
        - asset: assets/font/Alegreya/Alegreya-Italic-VariableFont_wght.ttf
        - asset: assets/font/Alegreya/Alegreya-VariableFont_wght.ttf
     
    - family: AlegreyaSans
      fonts:
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Black.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Bold.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-ExtraBold.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Light.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Medium.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Regular.ttf
        - asset: assets/font/AlegreyaSans/AlegreyaSans-Thin.ttf