name: mind_horizon
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8
  audioplayers: ^6.4.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^5.0.0

flutter:

  
  uses-material-design: true

  assets:
    - asset/gif/
    - asset/img/
   

  
  fonts:
    - family: Poppins
      fonts:
        - asset: asset/font/Poppins/Poppins-Black.ttf
        - asset: asset/font/Poppins/Poppins-Bold.ttf
        - asset: asset/font/Poppins/Poppins-ExtraBold.ttf
        - asset: asset/font/Poppins/Poppins-ExtraLight.ttf
        - asset: asset/font/Poppins/Poppins-Light.ttf
        - asset: asset/font/Poppins/Poppins-Medium.ttf
        - asset: asset/font/Poppins/Poppins-Regular.ttf
        - asset: asset/font/Poppins/Poppins-SemiBold.ttf
        - asset: asset/font/Poppins/Poppins-Thin.ttf

    - family: Alegreya
      fonts:
        - asset: asset/font/Alegreya/Alegreya-Italic-VariableFont_wght.ttf
        - asset: asset/font/Alegreya/Alegreya-VariableFont_wght.ttf
     
    - family: AlegreyaSans
      fonts:
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Black.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Bold.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-ExtraBold.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Light.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Medium.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Regular.ttf
        - asset: asset/font/AlegreyaSans/AlegreyaSans-Thin.ttf